# Test configuration for v10r Docker Compose environment
# This file provides environment variables for testing

# PostgreSQL test database settings
POSTGRES_HOST: test-postgres
POSTGRES_PORT: 5432
POSTGRES_USER: v10r_test
POSTGRES_PASSWORD: test_password_123
POSTGRES_DB: v10r_test_db

# External port mappings for testing from host
POSTGRES_EXTERNAL_PORT: 15432
REDIS_EXTERNAL_PORT: 16379
INFINITY_EXTERNAL_PORT: 18080

# Redis test settings
REDIS_HOST: test-redis
REDIS_PORT: 6379

# Mock Infinity settings
INFINITY_HOST: mock-infinity
INFINITY_PORT: 80
INFINITY_ENDPOINT: http://mock-infinity/v1/embeddings

# Test environment flags
TEST_MODE: "true"
LOG_LEVEL: "DEBUG"
SKIP_MIGRATIONS: "false"

# v10r specific test settings
V10R_CONFIG_PATH: "/test-data/v10r-test-config.yaml"
V10R_BATCH_SIZE: "10"
V10R_MAX_RETRIES: "2"
V10R_TIMEOUT: "30" 