name: Run Tests

on:
  push:
    branches-ignore:
      - fuzu_production
      - fuzu_staging
      - barona_qa
      - barona_production

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Start services
        run: docker-compose -f docker-compose.test.yml up -d

      - name: Wait for services to be healthy
        run: |
          echo "Waiting for PostgreSQL..."
          until docker-compose -f docker-compose.test.yml exec -T test-postgres pg_isready -U v10r_test -d v10r_test_db; do sleep 1; done
          echo "Waiting for Redis..."
          until docker-compose -f docker-compose.test.yml exec -T test-redis redis-cli ping | grep PONG; do sleep 1; done
          echo "Waiting for Mock Infinity..."
          until docker-compose -f docker-compose.test.yml exec -T mock-infinity python -c "import urllib.request; urllib.request.urlopen('http://localhost/health').read()"; do sleep 1; done
          echo "All services are healthy!"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -e '.[dev]'

      - name: Run tests
        run: |
          source .venv/bin/activate
          make test-all
